### ISSUE TITLE
Why is there a queue.py

### ISSUE THREAD

**Issue by qwert42** [Coco-Yang/robotics_hw4#1]
It seems like a Python standard library file.

**Comment by Coco-Yang** [comment]
I find that source code file online. (available at: https://hg.python.org/cpython/file/3.5/Lib/queue.py)

I want to use the class named 'PriorityQueue' in that file to help implement find_shortest_path method of class 'Graph'.

Can we use that?

**Comment by qwert42** [comment]
Sure. You can do that by `from queue import PriorityQueue` without the file explicitly being present.

Also, there's heapq module in Python.

**Comment by Coco-Yang** [comment]
Got it! Thanks.

I have deleted file queue.py
